[window]
opacity = 0.95
dynamic_padding = true

[window.padding]
x = 10
y = 10

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[colors.primary]
background = "0x1d2021"
foreground = "0xd4be98"

[colors.normal]
black   = "0x32302f"
red     = "0xea6962"
green   = "0xa9b665"
yellow  = "0xd8a657"
blue    = "0x7daea3"
magenta = "0xd3869b"
cyan    = "0x89b482"
white   = "0xd4be98"

[colors.bright]
black   = "0x32302f"
red     = "0xea6962"
green   = "0xa9b665"
yellow  = "0xd8a657"
blue    = "0x7daea3"
magenta = "0xd3869b"
cyan    = "0x89b482"
white   = "0xd4be98"
